# Generated by Django 2.2.1 on 2019-10-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WpWpdevartImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('image_h', models.TextField(blank=True, null=True)),
                ('image_w', models.TextField(blank=True, null=True)),
                ('image_size', models.TextField(blank=True, null=True)),
                ('image_type', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=4048, null=True)),
            ],
            options={
                'db_table': 'wp_wpdevart_images',
                'managed': False,
            },
        ),
    ]
