# Generated by Django 2.2.7 on 2019-11-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp', '0004_extra_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('vid', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
