# Generated by Django 3.0.2 on 2020-01-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav_details',
            name='date',
            field=models.DateField(),
        ),
    ]
